#!/usr/bin/env python3
"""make_team_logos -- the team logos in the ground station's header.

    python tools/scripts/make_team_logos.py "../../presentations/assets/ti_logo.jpg" "../../presentations/assets/asta_logo.png"

Writes uav_groundstation/uav_groundstation/team_logos.py (generated; do not
edit it): each logo shrunk to HEIGHT_PX tall -- three times the 32 px it is
drawn at, so it stays sharp on a high-DPI laptop -- as a data: URI. The page
embeds them rather than fetching them: at the flight line there is nothing to
fetch from. Needs Pillow; a laptop tool, run when a logo changes.
"""
import base64
import io
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "uav_groundstation", "uav_groundstation",
                   "team_logos.py")
HEIGHT_PX = 96
NAMES = {"ti_logo": "Team Inspiration",
         "asta_logo": "Advancing Science, Technology & Art"}


def data_uri(path):
    im = Image.open(path)
    im = im.convert("RGBA" if im.mode in ("RGBA", "LA", "P") else "RGB")
    w = round(im.width * HEIGHT_PX / im.height)
    im = im.resize((w, HEIGHT_PX), Image.LANCZOS)
    buf = io.BytesIO()
    if im.mode == "RGBA":
        im.save(buf, "PNG", optimize=True)
        mime = "image/png"
    else:
        im.save(buf, "JPEG", quality=88, optimize=True)
        mime = "image/jpeg"
    return "data:%s;base64,%s" % (mime, base64.b64encode(buf.getvalue()).decode("ascii")), w


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    rows = []
    for path in sys.argv[1:]:
        stem = os.path.splitext(os.path.basename(path))[0]
        uri, w = data_uri(path)
        rows.append((NAMES.get(stem, stem), uri))
        print("%-40s %dx%d  %d bytes" % (NAMES.get(stem, stem), w, HEIGHT_PX, len(uri)))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write('"""team_logos -- the logos in the ground station\'s header.\n\n'
                "GENERATED by tools/scripts/make_team_logos.py from %s; do not edit.\n"
                "Each is (name, data: URI), %d px tall.\n\"\"\"\n\n"
                % (", ".join(os.path.basename(p) for p in sys.argv[1:]), HEIGHT_PX))
        f.write("LOGOS = [\n")
        for name, uri in rows:
            f.write("    (%r,\n" % name)
            for k in range(0, len(uri), 88):
                f.write('     "%s"\n' % uri[k:k + 88])
            f.write("     ),\n")
        f.write("]\n")
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
